### ISSUE TITLE
Android Sprint Deliverable Checklist

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#192]
This ticket is for my sanity and to track and communicate progress on the key deliverables of this sprint.

- [x] commit, review and merge all demo app changes [1h]
- [x] create checkpoints [2h]
- [x] commit, review and merge all SDK changes [30m]
- [x] commit, review and merge all Wallet changes [15m]
- [x] tag SDK version 1.1.0-beta04 [5m]
- [x] create release notes for the SDK [30m]
- [x] create release notes for the wallet [15m]
- [x] publish mainnet release SDK version 1.1.0-beta04 to bintray w/ release notes [15m]
- [x] publish testnet release SDK version 1.1.0-beta04 to bintray w/ release notes [15m]
- [x] update changelog.md for the wallet [5m]
- [x] create changelog.md for the sdk [5m]
- [x] publish playstore build with release notes [30m]
- [x] announce release in the internal company wallet channel [5m]
- [x] (optional) announce SDK release in the public wallet channels [10m]
- [ ] (optional) tag or release demo app [5m]
- [x] (optional) announce demo app update in the public wallet channels [10m]
