### ISSUE TITLE
Revised TX Detail Screen

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#98]
As a user, I would like to be able to see the details of my transactions to accurately display

- [ ] The amount I sent or received
- [ ] Who I sent them to
- [ ] When I sent or receive funds
- [ ] The memo associated with the transaction
- [ ] The status of transaction confirmation including confirmation blocks
- [ ] The status of change associated with a sent transaction
- [ ] the amount of change I can expect
- [ ] Implemented with the provided designs

@geffenz Please comment the finalized designs in a thread here when they are complete.

**Comment by gmale** [comment]
This is dev complete and probably just needs a bit of refinement.
